import { StyleSheet, Dimensions } from "react-native";

export const styles = (theme) => StyleSheet.create({
    changePasswordHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
    },
    scrollContainer: {
        padding: theme.spacing.sm,
        paddingBottom: theme.spacing.xl,
        width: '100%'
    },
    profileScrollContainer: {
        padding: theme.spacing.sm,
        paddingBottom: theme.spacing.xl,
    },
    registerLink: {
        alignSelf: 'center',
    },
    registerText: {
        ...theme.typography.body,
        color: theme.colors.text,
    },
    registerHighlight: {
        color: theme.colors.primary,
        textDecorationLine: 'underline',
    },
    description: {
        fontSize: 16,
        lineHeight: 24,
        color: theme.colors.text,
        marginTop: theme.spacing.xs,
    },
    form: {
        flex: 1,
        paddingHorizontal: theme.spacing.lg,
        marginTop: theme.spacing.xl * 2,
    },
    button: {
        backgroundColor: theme.colors.primary,
        paddingVertical: theme.spacing.md,
        borderRadius: theme.borderRadius.lg,
        alignItems: 'center',
        marginBottom: theme.spacing.md,
        ...theme.shadows.sm,
    },
    buttonDisabled: {
        opacity: 0.5,
    },
    centered: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    conversationItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: theme.spacing.lg,
        paddingVertical: theme.spacing.md,
        backgroundColor: theme.colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
    },
    avatarContainer: {
        position: 'relative',
        marginRight: theme.spacing.md,
    },
    unreadBadge: {
        position: 'absolute',
        top: -2,
        right: -2,
        minWidth: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: theme.colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 4,
        borderWidth: 2,
        borderColor: theme.colors.surface,
    },
    bottomRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    lastMessage: {
        flex: 1,
        fontSize: theme.typography.body.fontSize,
        color: theme.colors.textLight,
        marginRight: theme.spacing.sm,
    },
    unreadLastMessage: {
        fontWeight: '600',
        color: theme.colors.text,
    },
    unreadDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: theme.colors.primary,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 60,
        paddingHorizontal: theme.spacing.lg,
    },
    emptyText: {
        fontSize: theme.typography.h3.fontSize,
        color: theme.colors.textLight,
        marginTop: theme.spacing.md,
        marginBottom: theme.spacing.lg,
    },
    startChatButton: {
        backgroundColor: theme.colors.primary,
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.xl,
        borderRadius: theme.borderRadius.lg,
        ...theme.shadows.md,
    },
    startChatButtonText: {
        fontSize: theme.typography.body.fontSize,
        fontWeight: '600',
        color: '#fff',
    },
    errorText: {
        color: theme.colors.error,
        marginBottom: theme.spacing.md,
    },
    conversationInfo: {
        flex: 1,
    },
    topRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    listContent: {
        paddingVertical: theme.spacing.sm,
    },
    headerTitle: {
        fontSize: theme.typography.h2.fontSize,
        fontWeight: '700',
        color: theme.colors.text,
    },
    headerButton: {
        padding: theme.spacing.sm,
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.colors.background,
    },
    name: {
        fontSize: theme.typography.h3.fontSize,
        fontWeight: '600',
        color: theme.colors.text,
        flex: 1,
        marginRight: theme.spacing.sm,
    },
    timestamp: {
        fontSize: theme.typography.caption.fontSize,
        color: theme.colors.textLight,
    },
    unreadText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#fff',
    },
    container: {
        flex: 1,
        padding: theme.spacing.sm,
        backgroundColor: theme.colors.background,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: theme.colors.text,
    },
    resultsContainer: {
        flex: 1,
        marginTop: theme.spacing.md,
    },
    placeholderText: {
        fontSize: 16,
        color: theme.colors.textLight,
        marginBottom: theme.spacing.xs,
        fontStyle: 'italic',
    },

    listingPlaceholderText: {
        marginTop: theme.spacing.sm,
        fontSize: 16,
        color: theme.colors.textLight,
    },
    card: {
        width: '100%',
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.xs,
        padding: theme.spacing.sm,
        alignItems: 'center',
        ...theme.shadows.md,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        marginBottom: theme.spacing.lg,
    },
    iconButton: {
        padding: theme.spacing.sm,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.md,
        ...theme.shadows.sm,
    },
    editButton: {
        ...theme.shadows.sm,
    },
    editButtonText: {
        color: 'black',
        fontWeight: '600',
        fontSize: 16,
    },
    profileEditButtonText: {
        color: theme.colors.text,
        fontWeight: '600',
        fontSize: 16,
    },
    infoContainer: {
        width: '100%',
    },
    infoRow: {
        marginBottom: theme.spacing.md,
    },
    label: {
        fontSize: 14,
        fontWeight: '500',
        color: theme.colors.text,
        marginBottom: theme.spacing.xs,
    },
    value: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.text,
        paddingVertical: theme.spacing.xs,
    },
    editContainer: {
        width: '100%',
    },
    inputWrapper: {
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.lg,
        backgroundColor: theme.colors.background,
        justifyContent: 'center',
        ...theme.shadows.sm,
    },
    saveButtonWrapper: {
        marginTop: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        overflow: 'hidden',
        ...theme.shadows.md,
    },
    saveButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: theme.spacing.lg,
        paddingHorizontal: theme.spacing.xl,
    },
    saveButtonText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
    },
    actions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 16,
    },
    titleGradient: {
        paddingVertical: theme.spacing.xs,
        paddingHorizontal: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        ...theme.shadows.md,
    },
    title: {
        fontSize: 20,
        fontWeight: '700',
        color: '#fff',
        letterSpacing: 0.5,
        padding: 5,
    },
    actionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: theme.spacing.sm,
    },
    gradient: {
        flexDirection: "row",
        borderRadius: theme.borderRadius.xs,
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.md,
        alignItems: "center",
        borderWidth: 1,
        borderColor: theme.colors.surface,
        backgroundColor: theme.colors.background,
    },
    text: {
        fontSize: theme.typography.body.fontSize,
        color: theme.colors.text,
        fontWeight: "600",
    },
    plus: {
        fontSize: theme.typography.body.fontSize,
        marginRight: theme.spacing.xs,
        fontWeight: "700",
    },
    buttonStyles: {
    },
    gradientButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.md,
        ...theme.shadows.sm,
        borderWidth: 1,
    },
    profileGradientButton: {
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        backgroundColor: theme.colors.surface,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    sellButton: {
        marginRight: theme.spacing.md,
    },
    buttonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    actionButton: {
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.lg,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.md,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    actionButtonText: {
        color: theme.colors.text,
        fontWeight: '500',
        fontSize: 16,
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.surface,
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        marginBottom: theme.spacing.sm,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    searchIcon: {
        marginRight: theme.spacing.sm,
    },
    searchText: {
        fontSize: 16,
        color: theme.colors.textLight,
    },
    section: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.sm,
        marginBottom: theme.spacing.sm,
        ...theme.shadows.md,
        width: "100%",
    },

    settingSection: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.md,
        marginBottom: theme.spacing.sm,
        ...theme.shadows.md,
        width: "100%",
    },
    section2: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.sm,
        marginBottom: theme.spacing.sm,
        ...theme.shadows.md,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    // gridItem: {
    //     width: ((Dimensions.get("window").width - theme.spacing.sm * 3) / 2),
    //     marginBottom: 12,
    // },
    listingTopSection: {
        display: 'flex',
        flexDirection: "row",
        justifyContent: 'space-between',
        marginBottom: theme.spacing.sm,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.md,
        marginBottom: theme.spacing.sm,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    multiActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.md,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    backButtonText: {
        marginLeft: theme.spacing.xs,
        fontSize: 16,
        color: theme.colors.text,
        fontWeight: '500',
    },
    categoryCard: {
        width: '48%',
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.md,
    },
    categoryImagePlaceholder: {
        width: '100%',
        height: 120,
        backgroundColor: theme.colors.background,
        borderRadius: theme.borderRadius.md,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: theme.spacing.sm,
    },
    categoryName: {
        fontSize: 16,
        fontWeight: '500',
        color: theme.colors.text,
        textAlign: 'center',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: theme.spacing.sm,
        justifyContent: 'space-between',
    },
    menuButton: {
        padding: theme.spacing.sm,
        marginRight: theme.spacing.md,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.md,
        ...theme.shadows.sm,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: theme.spacing.md,
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: theme.spacing.md,
    },
    buttonIcon: {
        marginRight: theme.spacing.xs,
    },
    flexOne: {
        flex: 1,
    },
    imagePreviewContainer: {
        flexDirection: 'row',
        marginTop: theme.spacing.sm,
    },
    imageWrapper: {
        position: 'relative',
        marginRight: theme.spacing.sm,
    },
    previewImage: {
        width: 80,
        height: 80,
        borderRadius: theme.borderRadius.md,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    removeImageButton: {
        position: 'absolute',
        top: -6,
        right: -6,
        backgroundColor: theme.colors.surface,
        borderRadius: 12,
        ...theme.shadows.sm,
    },
    inputGroup: {
        marginBottom: theme.spacing.md,
    },
    input: {
        height: 48,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.md,
        paddingHorizontal: theme.spacing.md,
        paddingVertical: theme.spacing.sm,
        fontSize: 16,
        color: theme.colors.text,
        backgroundColor: theme.colors.surface,
    },
    pickerInput : {
        backgroundColor: theme.colors.surface,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.md,
        color: theme.colors.text,
    },
    textArea: {
        height: 100,
        textAlignVertical: 'top',
        paddingTop: theme.spacing.md,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    marginRight: {
        marginRight: theme.spacing.md,
    },
    pickerContainer: {
        position: 'relative',
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.md,
        backgroundColor: theme.colors.surface,
        justifyContent: 'center',
    },
    picker: {
        height: 48,
        color: theme.colors.text,
    },
    pickerIcon: {
        position: 'absolute',
        right: theme.spacing.md,
        top: 14,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    locationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.sm,
        backgroundColor: theme.colors.surface,
        borderWidth: 1,
        borderColor: theme.colors.primary,
        borderRadius: theme.borderRadius.md,
        ...theme.shadows.sm,
    },
    locationButtonText: {
        marginLeft: theme.spacing.xs,
        color: theme.colors.primary,
        fontWeight: '500',
    },
    submitButtonWrapper: {
        marginTop: theme.spacing.lg,
        ...theme.shadows.md,
        borderWidth: 1,
        borderColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
    },
    submitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
    },
    submitText: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.text,
    },
    imageCarousel: {
        marginBottom: theme.spacing.sm,
        borderRadius: theme.borderRadius.lg,
        overflow: 'hidden',
        ...theme.shadows.md,
    },
    image: {
        width: "100%",
        height: 250,
        resizeMode: 'cover',
        borderRadius: theme.borderRadius.lg,
        marginRight: theme.spacing.sm,
    },
    imagePlaceholder: {
        width: '100%',
        height: 200,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: theme.spacing.sm,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderStyle: 'dashed',
        ...theme.shadows.sm,
    },
    infoCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        padding: theme.spacing.lg,
        marginBottom: theme.spacing.sm,
        ...theme.shadows.md,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: theme.spacing.md,
    },
    productName: {
        fontSize: 22,
        fontWeight: '700',
        color: theme.colors.text,
        flex: 1,
        marginRight: theme.spacing.md,
    },
    productPrice: {
        fontSize: 24,
        fontWeight: '700',
        color: theme.colors.primary,
    },
    metaContainer: {
        marginTop: theme.spacing.sm,
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: theme.spacing.xs,
    },
    metaText: {
        marginLeft: theme.spacing.sm,
        fontSize: 14,
        color: theme.colors.textLight,
    },
    sellerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: theme.spacing.sm,
    },
    sellerInfo: {
        marginLeft: theme.spacing.md,
    },
    sellerName: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
    },
    sellerJoined: {
        fontSize: 14,
        color: theme.colors.textLight,
        marginTop: 2,
    },
    contactButtonWrapper: {
        marginTop: theme.spacing.sm,
        borderRadius: theme.borderRadius.lg,
        overflow: 'hidden',
        ...theme.shadows.md,
    },
    contactButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: theme.spacing.lg,
        paddingHorizontal: theme.spacing.xl,
    },
    contactButtonText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
    },
    settingCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        paddingHorizontal: theme.spacing.sm,
        ...theme.shadows.md,
    },
    settingItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.sm,
    },
    settingItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    settingIcon: {
        marginRight: theme.spacing.md,
    },
    settingLabel: {
        fontSize: 16,
        color: theme.colors.text,
    },
    divider: {
        height: 1,
        backgroundColor: theme.colors.border,
        marginLeft: 52,
    },
    logoutText: {
        fontSize: 16,
        color: theme.colors.error,
        fontWeight: '500',
    },
    versionText: {
        fontSize: 16,
        color: theme.colors.textLight,
    },
    profileEditButton: {
        ...theme.shadows.sm,
    },
    cameraButtonOverlay: {
        position: 'absolute',
        top: 8,
        right: 105,
        zIndex: 10,
        backgroundColor: 'rgba(0,0,0,0.6)',
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        ...theme.shadows.sm,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '80%',
        backgroundColor: theme.colors.surface,
        padding: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        ...theme.shadows.md,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: theme.spacing.md,
    },
    modalButton: {
        backgroundColor: theme.colors.primary,
        padding: theme.spacing.md,
        borderRadius: theme.borderRadius.md,
        marginBottom: theme.spacing.sm,
        alignItems: 'center',
    },
    modalButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    modalCancelButton: {
        backgroundColor: theme.colors.border,
        padding: theme.spacing.md,
        borderRadius: theme.borderRadius.md,
        alignItems: 'center',
    },
    modalCancelText: {
        color: theme.colors.text,
        fontSize: 16,
    },
    profileCard: {
        backgroundColor: theme.colors.background,
        borderRadius: 28,
        // padding: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 5,
        // marginHorizontal: 5,
        // marginTop: 20,
    },
    profileImageContainer: {
        alignItems: 'center',
        marginBottom: 24,
        position: 'relative',
    },
    profileImage: {
        width: 120,
        height: 120,
        borderRadius: 60,
        marginBottom: theme.spacing.lg,
        borderWidth: 3,
        borderColor: theme.colors.primary,
        ...theme.shadows.md,
    },
    profileInfoContainer: {
        marginTop: 8,
    },
    profileInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    infoIcon: {
        marginRight: 12,
    },
    profileLabel: {
        width: 80,
        fontSize: 14,
        color: theme.colors.text,
        fontWeight: '500',
    },
    profileValue: {
        flex: 1,
        fontSize: 16,
        color: theme.colors.text,
        fontWeight: '400',
    },
    profileEditContainer: {
        marginTop: 8,
    },
    profileInputGroup: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 6,
    },
    profileInputWrapper: {
        borderWidth: 1,
        borderColor: '#dee2e6',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: theme.colors.background,
    },
    profileInput: {
        fontSize: 16,
        color: theme.colors.text,
        padding: 0,
    },
    profileSaveButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 30,
        marginTop: 16,
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    profileSaveButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#fff',
    },
    conversationContainer: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    conversationHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: theme.spacing.md,
        paddingVertical: theme.spacing.sm,
        backgroundColor: theme.colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    headerLeft: {
        flexDirection: "row",
        alignItems: "center",
    },
    conversationBackButton: {
        marginRight: theme.spacing.sm,
        padding: theme.spacing.xs,
    },
    individualConversationInfo: {
        flexDirection: "row",
        alignItems: "center",
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: theme.colors.primary,
        marginRight: theme.spacing.sm,
        justifyContent: "center",
        alignItems: "center",
    },
    avatarText: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "600",
    },
    conversationName: {
        fontSize: theme.typography.h3.fontSize,
        fontWeight: "600",
        color: theme.colors.text,
    },
    conversationIconButton: {
        padding: theme.spacing.xs,
    },
    messagesList: {
        paddingHorizontal: theme.spacing.md,
        paddingTop: theme.spacing.md,
        paddingBottom: theme.spacing.sm,
    },
    messageRow: {
        marginBottom: theme.spacing.md,
        flexDirection: "row",
    },
    myMessageRow: {
        justifyContent: "flex-end",
    },
    messageBubble: {
        maxWidth: "75%",
        padding: theme.spacing.sm,
        borderRadius: theme.borderRadius.lg,
        ...theme.shadows.sm,
    },
    myBubble: {
        backgroundColor: theme.colors.primary,
        borderBottomRightRadius: theme.borderRadius.xs,
    },
    otherBubble: {
        backgroundColor: theme.colors.surface,
        borderBottomLeftRadius: theme.borderRadius.xs,
    },
    messageText: {
        fontSize: theme.typography.body.fontSize,
        lineHeight: theme.typography.body.lineHeight,
        color: theme.colors.text,
    },
    myMessageText: {
        color: "#fff",
    },
    senderName: {
        fontSize: theme.typography.caption.fontSize,
        fontWeight: "600",
        color: theme.colors.textLight,
        marginBottom: 2,
    },
    conversationTimestamp: {
        fontSize: 12,
        color: theme.colors.textLight,
        alignSelf: "flex-end",
        marginTop: 4,
    },
    myTimestamp: {
        color: "rgba(255,255,255,0.7)",
    },
    inputContainer: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: theme.spacing.md,
        paddingVertical: theme.spacing.sm,
        backgroundColor: theme.colors.surface,
        borderTopWidth: 1,
        borderTopColor: theme.colors.border,
    },
    textInput: {
        flex: 1,
        minHeight: 40,
        maxHeight: 100,
        backgroundColor: theme.colors.background,
        borderRadius: theme.borderRadius.lg,
        paddingHorizontal: theme.spacing.md,
        paddingVertical: theme.spacing.sm,
        marginRight: theme.spacing.sm,
        fontSize: theme.typography.body.fontSize,
        color: theme.colors.text,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    sendButton: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: theme.colors.primary,
        justifyContent: "center",
        alignItems: "center",
        ...theme.shadows.sm,
    },
    sendButtonDisabled: {
        opacity: 0.5,
    },
    centerContent: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    conversationErrorText: {
        color: theme.colors.error,
        marginBottom: theme.spacing.md,
    },
    conversationBackButtonText: {
        marginLeft: theme.spacing.xs,
        fontSize: 16,
        color: theme.colors.text,
        fontWeight: "500",
    },
    outerContainer: {
        flex: 1,
        paddingHorizontal: theme.spacing.md,
        marginTop: theme.spacing.xl * 5,
        backgroundColor: theme.colors.background,
    },

    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },

    loadingText: {
        ...theme.typography.body,
        color: theme.colors.text,
        marginTop: theme.spacing.md,
    },
    formWrapper: {
        backgroundColor: theme.colors.background,
    },
    loginTitle: {
        ...theme.typography.h2,
        color: theme.colors.text,
        marginBottom: theme.spacing.lg,
    },
    loginLabel: {
        ...theme.typography.caption,
        color: theme.colors.textLight,
        marginBottom: theme.spacing.xs,
    },
    loginInput: {
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.sm,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        fontSize: theme.typography.body.fontSize,
        color: theme.colors.text,
        backgroundColor: theme.colors.surface,
    },
    loginButton: {
        backgroundColor: theme.colors.primary,
        padding: theme.spacing.md,
        borderRadius: theme.borderRadius.lg,
        alignItems: 'center',
        marginBottom: theme.spacing.md,
        ...theme.shadows.sm,
    },
    loginButtonText: {
        color: '#fff',
        fontSize: theme.typography.body.fontSize,
        fontWeight: '600',
        textAlign: 'center',
    },
    loginRegisterText: {
        // ...theme.typography.body,
        color: theme.colors.text,
    },
    listProductContainer: {
        flexDirection: "column",
        padding: 12,
        backgroundColor: "#fff",
        borderRadius: 8,
        marginBottom: 8,
        gap: 12,
    },
    list_product_image: {
        width: 170,
        height: 170,
        borderRadius: 8,
        backgroundColor: "#eee",
    },
    details: {
        flex: 1,
    },
    listing_info_card: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    listProductName: {
        fontSize: 16,
        fontWeight: "600",
        flexShrink: 1,
        color: theme.colors.text,
    },
    price: {
        fontSize: 16,
        color: theme.colors.text,
        // marginTop: 4,
    },
    category: {
        fontSize: 12,
        color: "#777",
        marginTop: 2,
    },
    drawerHeader: {
        // padding: 20,
        paddingLeft: 16,
        paddingVertical: 16,
    },
    drawerHeaderText: {
        fontSize: 20,
        fontWeight: "600",
        color: theme.colors.text,
    },
    drawerItem: {
        marginVertical: 0,
        paddingVertical: 0,
    },
    drawerRow: {
        paddingVertical: 14,
        paddingHorizontal: 20,
        flexDirection: "row",
        alignItems: "center",
    },
    drawerLabel: {
        fontSize: 16,
        color: theme.colors.text,
    },
    drawerLogout: {
        color: "red",
    },
    registerPageText: {
        // ...theme.typography.body,
        color: theme.colors.text,
    },
    registerTitle: {
        ...theme.typography.h2,
        color: theme.colors.text,
        marginBottom: theme.spacing.lg,
    },
    registerLabel: {
        ...theme.typography.caption,
        color: theme.colors.textLight,
        marginBottom: theme.spacing.xs,
    },
    registerInput: {
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.sm,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        fontSize: theme.typography.body.fontSize,
        color: theme.colors.text,
        backgroundColor: theme.colors.surface,
    },
    registerButton: {
        backgroundColor: theme.colors.success,
        padding: theme.spacing.md,
        borderRadius: theme.borderRadius.lg,
        alignItems: 'center',
        marginBottom: theme.spacing.md,
        ...theme.shadows.sm,
    },
    registerButtonText: {
        color: '#fff',
        fontSize: theme.typography.body.fontSize,
        fontWeight: '600',
        textAlign: 'center',
    },
});