import { theme } from "../theme/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    scrollContainer: {
        padding: theme.spacing.sm,
        paddingBottom: theme.spacing.xl,
        width: '100%'
    },
    centered: {
        // borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    container: {
        flex: 1,
        padding: theme.spacing.sm,
        backgroundColor: theme.colors.background,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: theme.colors.text,
        // paddingVertical: theme.spacing.sm,
    },
    resultsContainer: {
        flex: 1,
        marginTop: theme.spacing.md,
    },
    placeholderText: {
        fontSize: 16,
        color: theme.colors.textLight,
        marginBottom: theme.spacing.md,
        fontStyle: 'italic',
    },
    card: {
        width: '100%',
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.xs,
        padding: theme.spacing.sm,
        alignItems: 'center',
        ...theme.shadows.md,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        marginBottom: theme.spacing.lg,
    },
    iconButton: {
        padding: theme.spacing.sm,
        backgroundColor: theme.colors.background,
        borderRadius: theme.borderRadius.md,
        ...theme.shadows.sm,
    },
    editButton: {
        // borderRadius: theme.borderRadius.lg,
        // overflow: 'hidden',
        ...theme.shadows.sm,
    },
    // gradientButton: {
    //     paddingVertical: theme.spacing.sm,
    //     paddingHorizontal: theme.spacing.lg,
    //     borderRadius: theme.borderRadius.lg,
    // },
    editButtonText: {
        color: 'black',
        fontWeight: '600',
        fontSize: 16,
    },
    profileImage: {
        width: 120,
        height: 120,
        borderRadius: 60,
        marginBottom: theme.spacing.lg,
        borderWidth: 3,
        borderColor: theme.colors.primary,
        ...theme.shadows.md,
    },
    infoContainer: {
        width: '100%',
    },
    infoRow: {
        marginBottom: theme.spacing.md,
    },
    label: {
        fontSize: 14,
        fontWeight: '500',
        color: theme.colors.text,
        marginBottom: theme.spacing.xs,
    },
    value: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.text,
        paddingVertical: theme.spacing.xs,
    },
    editContainer: {
        width: '100%',
    },
    inputWrapper: {
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.lg,
        backgroundColor: theme.colors.background,
        // paddingHorizontal: theme.spacing.md,
        // paddingVertical: theme.spacing.sm,
        justifyContent: 'center',
        ...theme.shadows.sm,
    },
    saveButtonWrapper: {
        marginTop: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        overflow: 'hidden',
        ...theme.shadows.md,
    },
    saveButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: theme.spacing.lg,
        paddingHorizontal: theme.spacing.xl,
    },
    saveButtonText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
    },
    actions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 16,
    },
    titleGradient: {
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        ...theme.shadows.md,
    },
    title: {
        fontSize: 20,
        fontWeight: '700',
        color: '#fff',
        letterSpacing: 0.5,
    },
    actionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: theme.spacing.sm,
    },
    gradientButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.md,
        // borderRadius: theme.borderRadius.md,
        ...theme.shadows.sm,
        borderWidth: 1,
    },
    sellButton: {
        marginRight: theme.spacing.md,
    },
    buttonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    actionButton: {
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.lg,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.md,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    actionButtonText: {
        color: theme.colors.text,
        fontWeight: '500',
        fontSize: 16,
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.surface,
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        marginBottom: theme.spacing.sm,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    searchIcon: {
        marginRight: theme.spacing.sm,
    },
    searchText: {
        fontSize: 16,
        color: theme.colors.textLight,
    },
    section: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.sm,
        marginBottom: theme.spacing.sm,
        ...theme.shadows.md,
        width: "100%",
    },
    section2: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        paddingVertical: theme.spacing.md,
        paddingHorizontal: theme.spacing.sm,
        marginBottom: theme.spacing.sm,
        ...theme.shadows.md,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    gridItem: {
        width: '48%',
        marginBottom: 12,
    },
    listingTopSection: {
        display: 'flex',
        flexDirection: "row",
        justifyContent: 'space-between',
        marginBottom: theme.spacing.sm,
    },

    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.md,
        marginBottom: theme.spacing.sm,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },

    multiActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.md,
        // marginBottom: theme.spacing.sm,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    backButtonText: {
        marginLeft: theme.spacing.xs,
        fontSize: 16,
        color: theme.colors.text,
        fontWeight: '500',
    },
    categoryCard: {
        width: '48%', // two columns with gap
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.lg,
        padding: theme.spacing.md,
        marginBottom: theme.spacing.md,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.md,
    },
    categoryImagePlaceholder: {
        width: '100%',
        height: 120,
        backgroundColor: theme.colors.background,
        borderRadius: theme.borderRadius.md,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: theme.spacing.sm,
    },
    categoryName: {
        fontSize: 16,
        fontWeight: '500',
        color: theme.colors.text,
        textAlign: 'center',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: theme.spacing.sm,
        justifyContent: 'space-between',
    },

    // header: {
    //     flexDirection: 'row',
    //     justifyContent: 'flex-start',
    //     marginBottom: theme.spacing.md,
    // },
    menuButton: {
        padding: theme.spacing.sm,
        marginRight: theme.spacing.md,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.md,
        ...theme.shadows.sm,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: theme.spacing.md,
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: theme.spacing.md,
    },
    buttonIcon: {
        marginRight: theme.spacing.xs,
    },
    flexOne: {
        flex: 1,
    },
    imagePreviewContainer: {
        flexDirection: 'row',
        marginTop: theme.spacing.sm,
    },
    imageWrapper: {
        position: 'relative',
        marginRight: theme.spacing.sm,
    },
    previewImage: {
        width: 80,
        height: 80,
        borderRadius: theme.borderRadius.md,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    removeImageButton: {
        position: 'absolute',
        top: -6,
        right: -6,
        backgroundColor: theme.colors.surface,
        borderRadius: 12,
        ...theme.shadows.sm,
    },
    inputGroup: {
        marginBottom: theme.spacing.md,
    },
    input: {
        height: 48,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.md,
        paddingHorizontal: theme.spacing.md,
        paddingVertical: theme.spacing.sm,
        fontSize: 16,
        color: theme.colors.text,
        backgroundColor: theme.colors.surface,
    },
    textArea: {
        height: 100,
        textAlignVertical: 'top',
        paddingTop: theme.spacing.md,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    marginRight: {
        marginRight: theme.spacing.md,
    },
    pickerContainer: {
        position: 'relative',
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: theme.borderRadius.md,
        backgroundColor: theme.colors.surface,
        justifyContent: 'center',
    },
    picker: {
        height: 48,
        color: theme.colors.text,
    },
    pickerIcon: {
        position: 'absolute',
        right: theme.spacing.md,
        top: 14,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    locationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.sm,
        backgroundColor: theme.colors.surface,
        borderWidth: 1,
        borderColor: theme.colors.primary,
        borderRadius: theme.borderRadius.md,
        ...theme.shadows.sm,
    },
    locationButtonText: {
        marginLeft: theme.spacing.xs,
        color: theme.colors.primary,
        fontWeight: '500',
    },
    submitButtonWrapper: {
        marginTop: theme.spacing.lg,
        ...theme.shadows.md,
    },
    submitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
    },
    submitText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
    },
});